<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Documentation</name>
   <tag></tag>
   <elementGuidId>c293776e-bd45-4ad6-b826-b69fdeacfa70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.breadcrumb-item > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Documentation')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;breadcrumb&quot;i >> internal:role=link[name=&quot;Documentation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dca60f6-1853-4e79-94a1-bd1012bbfcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.selenium.dev/documentation/</value>
      <webElementGuid>01cba79b-3f0c-49ab-a952-5c1e3fa03ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documentation</value>
      <webElementGuid>e1be423b-7275-49d5-a0ac-1e4fb828ab4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;td-page&quot;]/div[@class=&quot;container-fluid td-outer&quot;]/div[@class=&quot;td-main&quot;]/div[@class=&quot;row flex-xl-nowrap&quot;]/main[@class=&quot;col-12 col-md-9 col-xl-8 ps-md-5&quot;]/nav[@class=&quot;td-breadcrumbs&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item&quot;]/a[1]</value>
      <webElementGuid>99e99272-483c-4468-83bd-06d2fe615c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Documentation')]</value>
      <webElementGuid>5a001566-21a3-4c54-9812-ad79b09cee57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roadmap'])[2]/following::a[1]</value>
      <webElementGuid>196d237b-8709-4a4f-885d-f80d6fe86ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building a Custom Selenium Manager'])[1]/following::a[2]</value>
      <webElementGuid>746e5908-3b49-4c2f-8e32-b308732f4335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Manager'])[2]/preceding::a[1]</value>
      <webElementGuid>40a5cd56-1ce3-4c99-920f-db2feb944946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v4.0'])[1]/preceding::a[2]</value>
      <webElementGuid>09a657ec-8386-4314-b59e-fc30e34d82bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.selenium.dev/documentation/')])[2]</value>
      <webElementGuid>afe5c6b1-d09b-49ab-bb61-c5d74eeb2f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>972ad0ec-104a-4257-bb1b-003e4986cbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.selenium.dev/documentation/' and (text() = 'Documentation' or . = 'Documentation')]</value>
      <webElementGuid>0e936cc0-09b4-4bc9-9380-cb94eb3f2177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
